# scrutinizer config

tools:
    external_code_coverage: true

    php_code_sniffer: true

    php_cpd:
        enabled: true
        excluded_dirs: [vendor, app/tests]

    php_cs_fixer: true

    php_loc: 
        enabled:  true
        excluded_dirs: [vendor, app/tests]

    php_mess_detector: true

    php_pdepend: true

    php_analyzer: true

    sensiolabs_security_checker: true

before_commands:
    - "composer install --prefer-source"
