language: php
php:
  - 5.4

services: mongodb

before_script: 
    - phpenv config-add travis.ini
    - composer self-update
    - composer install

script: phpunit

branches:
    only:
        - master
