language: php

php:
  - 5.4

services: mongodb

branches:
    only:
        - master

before_script: 
    - phpenv config-add travis.ini
    - composer self-update
    - composer install

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar

    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
